### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zwr1617** [ZhengRui/pytorch-har#1]
你好博主，我在运行python train.py --batch_size 1000 --mode TESTTRAIN --init_lr .01，遇到了报错：
epoch: 4, iter: 13, loss: 0.12298957
epoch: 4, iter: 14, loss: 0.11001743
epoch 5, accuracy 0.91890055, recall-precision: 
tensor([[0.9456, 0.9830, 0.9857, 0.8187, 0.7951, 1.0000],
        [0.9730, 0.9586, 0.9367, 0.7913, 0.8668, 0.9871]])
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    train(**config)
  File "train.py", line 235, in train
    f'cache/models/{save_prefix}_epoch_{epoch}.state',
  File "/home/zwr-400g/anaconda3/envs/torch1.10.0py3.7.6/lib/python3.7/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/zwr-400g/anaconda3/envs/torch1.10.0py3.7.6/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zwr-400g/anaconda3/envs/torch1.10.0py3.7.6/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/models/run_epoch_5.state'

提示找不到cache/models/run_epoch_5.state文件，请问这个有什么办法么

**Comment by zwr1617** [comment]
解决了，新建cache/models文件夹就好了
